title: Lawrence Gilligan
#logo: /assets/img/headshot_circle.png

#headers: Contact
#description: Ltgilligan23@gmail.com

#headers: LinkedIn
#description: https://www.linkedin.com/in/larsgilligan/

headers: Location
description: New York, NY

show_downloads: false
theme: jekyll-theme-minimal
