title: Lawrence Gilligan
#logo: /assets/img/headshot_circle.png
description: locaiton: New York, NY contact: ltgilligan23@gmail.com linkedin: https://www.linkedin.com/in/larsgilligan/
show_downloads: false
theme: jekyll-theme-minimal
