title: Lawrence Gilligan
#logo: /assets/img/headshot_circle.png
description: | New York, NY | ltgilligan23@gmail.com | https://www.linkedin.com/in/larsgilligan/ |
show_downloads: false
theme: jekyll-theme-minimal
